/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "STM32F103C6_GPIO_Driver.h"
#include "sTM32F103x8.h"
#include "LCD.h"
#include "Key_Pad_Driver.h"
#include "STM32F103C6_EXTI_Driver.h"
unsigned int IRQ_Flag = 1;
void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
	RCC_AFIO_CLK_EN();
}

void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}
void EXTI9_callBack()
{
	IRQ_Flag = 1;
	LCD_Send_A_String("IRQ EXTI9 is happend _|- ");
	wait_ms(100);
}
int main(void)
{
	clock_init();
	LCD_Init();
	LCD_Clear_Screen();
	S_EXTI_Pin_Config_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9_PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_Rising;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_callBack;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_CFG);
	LCD_Clear_Screen();
	while (1)
	{
		if(IRQ_Flag)
		{
			LCD_Clear_Screen();
			IRQ_Flag= 0;
		}
	}
}

