/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//#define MCU_Act_As_Master
#define MCU_Act_As_Slave
#include "STM32F103C6_USART_Driver.h"
#include "STM32F103C6_SPI_Driver.h"
#include "sTM32F103x8.h"
#include "STM32F103C6_GPIO_Driver.h"
void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
	RCC_AFIO_CLK_EN();
}
uint16_t ch;
void SPI_Interrupt_Call_Back(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_Act_As_Slave
	if(irq_src.RXE)
	{
		ch=0xf;
		MCAL_SPI_Tx_Rx(SPI1, &ch, Disabled);
		MCAL_UART_SendData(USART1, &ch, Enable);
	}
#endif
}
void Uart_CallBack(void)
{
#ifdef MCU_Act_As_Master

	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);
	//Write zero to send data
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_Reset);
	MCAL_SPI_Tx_Rx(SPI1, &ch, Enabled);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_Set);
#endif
}

int main(void)
{
	S_UART_Config_t CFG;
	clock_init();
	CFG.USART_BaudRate = UART_BaudRate_115200;
	CFG.HwFlowCTRL = UART_HwFlowCTL_NONE;
	CFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	CFG.Parity = UART_Parity_NONE;
	CFG.Pay_Load_Length = UART_Pay_Load_Length_8bit;
	CFG.Stop_Bits = UART_Stop_Bits_1Bit;
	CFG.USART_Mode = UART_Mode_RX_TX;
	CFG.P_IRQ_CallBack = Uart_CallBack;
	MCAL_UART_Init(USART1,&CFG);
	MCAL_UART_GPIO_Set_Pins(USART1);
	//===============================SPI============================//
	//     PA4 : SPI1_NSS
	//	   PA5 : SPI1_SCK
	//	   PA6 : SPI1_MISO
	//	   PA7 : SPI1_MOSI
	S_SPI_Config_t SPICfg;
	SPICfg.CLock_Phase = SPI_Clock_Polarity_High_idel;
	SPICfg.CLock_Polarity =SPI_Clock_Phase_Trailing;
	SPICfg.Frame_Format = SPI_Frame_Format_MSB;
	SPICfg.Pay_Load_Length = SPI_Pay_Load_Length_8bit;
	SPICfg.SPI_Prescaler = SPI_Prescaler_By8;
	SPICfg.Communication_Mode = SPI_Direction_2lines;
#ifdef MCU_Act_As_Master
	SPICfg.Device_Mode = SPI_Mode_Master;
	SPICfg.IRQ_Enable =  SPI_IRQ_Enable_Non;
	SPICfg.NSS = SPI_NSS_Internal_Soft_Set;
	SPICfg.P_IRQ_CallBack = NULL;

	//SS PIN4
	GPIO_Pin_Config_t P_Config;
	P_Config.GPIO_Pin_Number = GPIO_PIN_4;
	P_Config.GPIO_Mode = GPIO_Mode_Output_PP;
	P_Config.GPIO_OUTPUT_Speed = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOA, &P_Config);
	//Write one
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_Set);
#endif
#ifdef MCU_Act_As_Slave
	SPICfg.Device_Mode = SPI_Mode_Slave;
	SPICfg.IRQ_Enable  = SPI_IRQ_Enable_Rx_only;
	SPICfg.NSS = SPI_NSS_Hard_Slave;
	SPICfg.P_IRQ_CallBack = SPI_Interrupt_Call_Back;
#endif
	MCAL_SPI_Init(SPI1, &SPICfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);
	while (1)
	{

	}
}
