/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "STM32F103C6_GPIO_Driver.h"
#include "sTM32F103x8.h"
void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
}
void Gpio_init(){
	GPIO_Pin_Config_t Pin_Cfg;
	//PA1 input HIGHZ
	Pin_Cfg.GPIO_Pin_Number = GPIO_PIN_1 ;
	Pin_Cfg.GPIO_Mode = GPIO_Mode_Input_FLO;
	MCAL_GPIO_Init(GPIOA, &Pin_Cfg);
	//PB1 OUTPUT Pull Push mode
	Pin_Cfg.GPIO_Pin_Number = GPIO_PIN_1 ;
	Pin_Cfg.GPIO_Mode = GPIO_Mode_Output_PP;
	Pin_Cfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10MHz;
	MCAL_GPIO_Init(GPIOB, &Pin_Cfg);
	//PA13 input HIGHZZ
	Pin_Cfg.GPIO_Pin_Number = GPIO_PIN_13 ;
	Pin_Cfg.GPIO_Mode = GPIO_Mode_Input_FLO;
	MCAL_GPIO_Init(GPIOA, &Pin_Cfg);
	//pB13  push pull
	Pin_Cfg.GPIO_Pin_Number = GPIO_PIN_13 ;
	Pin_Cfg.GPIO_Mode = GPIO_Mode_Output_PP;
	MCAL_GPIO_Init(GPIOB, &Pin_Cfg);
}
void wait_ms(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}
int main(void)
{

	uint32_t switch1 =0;
	clock_init();
	Gpio_init();


	while(1){
		if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0) && !switch1 )
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			switch1 = 1;
		}
		if((MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 1)  )
		{

			switch1 = 0;
		}
		if(MCAL_GPIO_ReadPin(GPIOA,GPIO_PIN_13) == 1)
		{
			MCAL_GPIO_TogglePin(GPIOB,GPIO_PIN_13);
		}
		wait_ms(1);

	}
}

