/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "STM32F103C6_GPIO_Driver.h"
#include "sTM32F103x8.h"
#include "LCD.h"
#include "Key_Pad_Driver.h"
#include "STM32F103C6_EXTI_Driver.h"
#include "STM32F103C6_USART_Driver.h"
unsigned int IRQ_Flag = 1;
void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
	RCC_AFIO_CLK_EN();
}

unsigned char ch;
void Uart_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);
}
int main(void)
{
	S_UART_Config_t CFG;
	clock_init();
	CFG.USART_BaudRate = UART_BaudRate_115200;
	CFG.HwFlowCTRL = UART_HwFlowCTL_NONE;
	CFG.IRQ_Enable = UART_IRQ_Enable_RXNEIE;
	CFG.Parity = UART_Parity_NONE;
	CFG.Pay_Load_Length = UART_Pay_Load_Length_8bit;
	CFG.Stop_Bits = UART_Stop_Bits_1Bit;
	CFG.USART_Mode = UART_Mode_RX_TX;
	CFG.P_IRQ_CallBack = Uart_CallBack;
	MCAL_UART_Init(USART1,&CFG);
	MCAL_UART_GPIO_Set_Pins(USART1);
	while (1)
	{

	}
}

