/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define RCC_Base   0x40021000
#define RCC_APB2EN *(volatile uint32_t *)(RCC_Base+0x18)
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)
#define RCC_CFGR  *(volatile uint32_t *)(RCC_Base+0x04)
#define RCC_CR    *(volatile uint32_t *)(RCC_Base+0x00)
int main(void)
{
//Enabling Clock
	RCC_APB2EN |= (1<<2);
//Configuring Clock
	RCC_CFGR |= (0b0110<<18);
	RCC_CFGR |= (0b100<<8);
	RCC_CFGR |= (0b101<<11);
	RCC_CFGR |= (0b10<<0);
	RCC_CR |= (0b1<<24);
//Init GPIOA
GPIOA_CRH &= 0xFF0FFFFF;
GPIOA_CRH |= 0x00200000;
while(1)
{
GPIOA_ODR |= 1<<13 ;
for (int i = 0; i < 5000; i++); // arbitrary delay
GPIOA_ODR &= ~(1<<13) ;
for (int i = 0; i < 5000; i++); // arbitrary delay
}
}
