/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define MCU_Act_As_Master
//#define MCU_Act_As_Slave
#include "STM32F103C6_USART_Driver.h"
#include "STM32F103C6_SPI_Driver.h"
#include "sTM32F103x8.h"
#include "STM32F103C6_GPIO_Driver.h"
#include "STM32F103C6_I2C_Driver.h"
#include "I2C_Slave_EEPROM.h"
void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
	RCC_AFIO_CLK_EN();
}
uint16_t ch;
void SPI_Interrupt_Call_Back(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_Act_As_Slave
	if(irq_src.RXE)
	{
		ch=0xf;
		MCAL_SPI_Tx_Rx(SPI1, &ch, Disabled);
		MCAL_UART_SendData(USART1, &ch, Enable);
	}
#endif
}
void Uart_CallBack(void)
{


	MCAL_UART_ReceiveData(USART1, &ch, Disable);
	MCAL_UART_SendData(USART1, &ch, Enable);
	//Write zero to send data
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_Reset);
	MCAL_SPI_Tx_Rx(SPI1, &ch, Enabled);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_Set);

}

int main(void)
{

	clock_init();

	//Test Case 1
	unsigned char ch1[]  = {0x1,0x2,0x3,0x4,0x5,0x6,0x7};
	unsigned char ch2[7] = {0};
	EEPROM_Init();
	EEPROM_Write_NBytes(0xAF, ch1, 7);
	EEPROM_Read_byte(0xAF, ch2, 7);
	for(int i = 0;i<1000000;i++)
	{
		//For testing test case2
	}
	//Test Case 2
	ch1[0] = 0xA;
	ch1[1] = 0xB;
	ch1[2] = 0xC;
	ch1[3] = 0xD;

	EEPROM_Write_NBytes(0xFFF,ch1,4);
	EEPROM_Read_byte(0xFFF,ch2,4);
	while (1)
	{

	}
}
