/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>

//Gpio
#define GPIO_BASE 0x40010800
#define GPIO_CRH *(volatile uint32_t *)(GPIO_BASE+0x04)
#define GPIO_CRL *(volatile uint32_t *)(GPIO_BASE+0x00)
#define GPIO_ODR *(volatile uint32_t *)(GPIO_BASE+0x0c)

//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE+0x18)
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE+0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE+0x00)


//EXTI 0x4001 0400 - 0x4001 07FF EXTI
#define EXTI_BASE 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_BASE+0x00)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_BASE+0x08)
#define EXTI_PR   *(volatile uint32_t *)(EXTI_BASE+0x014)

//AFIO
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *(volatile uint32_t *)(EXTI_BASE+0x08)

//NVIC
#define NVIC_BASE 0xE000E100
#define NVIC_EXTIE0 *(volatile uint32_t *)(NVIC_BASE+0x00)
void clock_init()
{
	RCC_APB2ENR |= (1<<2);   // Enable Gpio portA clock
	RCC_APB2ENR |= (1<<0);	//Alternate Function IO clock enabled
	}
void Gpio_init(){

	GPIO_CRH &=0xff0fffff;   // GPIO init
	GPIO_CRH |=0x00200000;    //pinA 13 output
	GPIO_CRL |=(1<<2);    // pinA0 input

}

int main(void)
{


	clock_init();
	Gpio_init();
	AFIO_EXTICR1 = 0;  //select the source input for EXTI0 pinA0

	EXTI_RTSR |= (1<<0);  //Rising trigger enabled


	EXTI_IMR |=(1<<0);  //Interrupt request from Line 0 is not maske
	//enable NVIC irq6 EXTI0
	NVIC_EXTIE0 |=(1<<6);

   while(1);
}

void   EXTI0_IRQHandler(void){

	GPIO_ODR ^=(1<<13);
	EXTI_PR |=(1<<0);	//cleared by writing a ‘1’ tp pending register
}
